version: '3'
services:
  db:
    image: "postgres:11"
    container_name: "hivemind"
    env_file:
    - ./.env
    ports:
    - "5432:5432"
    volumes:
    - ./database/sql/database.sql:/docker-entrypoint-initdb.d/database.sql
